(in-package :bib)
 
(defparameter *abbrev-list-a*
  '(("Journal of Nuclear Materials" "J. Nucl. Mater.")
    ("Science" "Sci.")
    ("Nature" "Nat.")
    ("Nature Communications" "Nat. Commun.")
    ("Physical Review Letters" "Phys. Rev. Lett.")
    ("Physics Reports" "Phys. Rep.")
    ("Physical Review" "Phys. Rev.")
    ("Physical Review A" "Phys. Rev. A")
    ("Physical Review B" "Phys. Rev. B")
    ("Physical Review E" "Phys. Rev. E")
    ("Journal of Physics: Condensed Matter" "J. Phys. Condens. Matter.")
    ("Physica A" "Physica A")
    ("Physica B" "Physica B")
    ("Physica C" "Physica C")
    ("Journal of the American Ceramic Society" "J. Am. Ceram. Soc.")
    ("Progress in Nuclear Science and Technology" "Prog. Nucl. Sci. Technol.")
    ("JOM" "JOM")
    ("Journal of Applied Physics" "J. Appl. Phys.")
    ("Physical Chemistry Chemical Physics" "Phys. Chem. Chem. Phys.")
    ("AIP Advances" "AIP Adv.")
    ("Frontiers of Physics" "Front. Phys.")
    ("The Journal of Chemical Physics" "J. Chem. Phys.")
    ("Reviews of Modern Physics" "Rev. Mod. Phys.")
    ("Nature Physics" "Nat. Phys.")
    ("Soviet Atomic Energy" "Sov. At. Energy")
    ("Journal of Solid State Chemistry" "J. Solid State Chem.")
    ("Computer Physics Communications" "Comput. Phys. Commun.")
    ("Europhysics Letters" "Europhys. Lett.")
    ("Transactions of the American Nuclear Society" "Trans Am Nucl Soc")
    ("Scripta Materialia" "Scripta. Mater.")
    ("Philosophical Magazine B" "Philos. Mag. B")
    ("Metallurgical and Materials Transactions A" "Metall. Mater. Trans. A")
    ("Journal of Magnetism and Magnetic Materials" "J. Magn. Magn. Mater.")
    ("Journal of Alloys and Compounds" "J. Alloys. Compd.")
    ("Journal of Physics C" "J. Phys. C")
    ("Nuclear Applications" "Nucl. Appl.")
    ))

