(in-package :bib)

(appendf *abbrev-list*
  '(("Behavioural Pharmacology" 		"Behav. Pharmacol.")
    ("Chemische Berichte"			"Chem. Ber.")
    ("Berichte der Bunsen-Gesellschaft Physical Chemistry Chemical Physics" "Ber. Bunsen-Ges. Phys. Chem")
    ("Biocatalysis and Biotransformation"	"Biocatal. Biotransform.")
    ("Biochemical Archives"			"Biochem. Arch.")
    ("Biochemical and Biophysical Research Communications" "Biochem. Biophys. Res. Commun.")
    ("Biochemistry and Cell Biology-Biochimie et Biologie Cellulaire" "Biochem. Cell Biol.")
    ("Biochemical Engineering Journal"		"Biochem. Eng. J.")
    ("Biochemical Genetics"			"Biochem. Genet.")
    ("Biochemical Journal"			"Biochem. J.")
    ("Biochemical Medicine and Metabolic Biology" "Biochem. Med. Metab. Biol.")
    ("Biochemistry and Molecular Biology International" "Biochem. Mol. Biol. Int.")
    ("Biochemical and Molecular Medicine"	"Biochem. Mol. Med.")
    ("Biochemical Pharmacology"			"Biochem. Pharmacol.")
    ("Biochemical Society Symposium"		"Biochem. Soc. Symp.")
    ("Biochemical Society Transactions"		"Biochem. Soc. Trans.")
    ("Biochemical Systematics and Ecology"	"Biochem. Syst. Ecol.")
    ("Biochimica et Biophysica Acta"		"Biochim. Biophys. Acta")
    ("Bioconjugate Chemistry"			"Bioconjugate Chem.")
    ("Bioelectrochemistry and Bioenergetics"	"Bioelectrochem. Bioenerg.")
    ("Biogenic Amines"				"Biog. Amines")
    ("Biological Chemistry"			"Biol. Chem.")
    ("Biological Chemistry Hoppe-Seyler"	"Biol. Chem. Hoppe-Seyler")
    ("Biological Membranes"			"Biol. Membr.")
    ("Biological and Pharmaceutical Bulletin"	"Biol. Pharm. Bull.")
    ("Biological Trace Element Research"	"Biol. Trace Elem. Res.")
    ("Biomass and Bioenergy"			"Biomass Bioenergy")
    ("Biomedical Chromatography"		"Biomed. Chromatogr.")
    ("Bio-Medical Materials and Engineering"	"Bio-Med. Mater. Eng.")
    ("Biomedical Microdevices"			"Biomed. Microdevices")
    ("Biomolecular Engineering"			"Biomol. Eng")
    ("Bioorganic Chemistry"			"Bioorg. Chem.")
    ("Bioorganicheskaya Khimiya"		"Bioorg. Khim")
    ("Bioorganic and Medicinal Chemistry"	"Bioorg. Med. Chem.")
    ("Bioorganic and Medicinal Chemistry Letters" "Bioorg. Med. Chem. Lett.")
    ("Biopharmaceutics and Drug Disposition"	"Biopharm. Drug Dispos.")
    ("Biophysical Chemistry"			"Biophys. Chem.")
    ("Biophysical Journal"			"Biophys. J.")
    ("Bioprocess Engineering"			"Bioprocess. Eng.")
    ("Bioremediation Journal"			"Biorem. J.")
    ("Bioresource Technology"			"Bioresour. Technol.")
    ("Bioscience Reports"			"Biosci. Rep.")
    ("Bioscience Biotechnology and Biochemistry" "Biosci., Biotechnol., Biochem.")
    ("Biosensors and Bioelectronics"		"Biosens. Bioelectron.")
    ("Biotechnic and Histochemistry"		"Biotech. Histochem.")
    ("Biotechnology Advances"			"Biotechnol. Adv.")
    ("Biotechnology and Applied Biochemistry"	"Biotechnol. Appl. Biochem.")
    ("Biotechnology and Bioengineering"		"Biotechnol. Bioeng.")
    ("Biotechnology and Biotechnological Equipment" "Biotechnol. Biotechnol. Equip.")
    ("Biotechnology Letters"			"Biotechnol. Lett.")
    ("Biotechnology Progress"			"Biotechnol. Progr.")
    ("Biotechnology Techniques"			"Biotechnol. Tech.")
    ("Boletin de la Sociedad Chilena de Quimica" "Bol. Soc. Chil. Quim.")
    ("British Ceramic Transactions"		"Br. Ceram. Trans.")
    ("British Corrosion Journal"		"Br. Corros. J.")
    ("British Jornal of Pharmacology"		"Br. J. Pharmacol.")
    ("Brennstoff-Warme-Kraft"			"Brennst.-Warme-Kraft")
    ("Bulletin of the Chemical Society of Japan" "Bull. Chem. Soc. Jpn.")
    ("Bulletin of Electrochemistry"		"Bull. Electrochem.")
    ("Bulletin of Environment Contamination and Toxicology" "Bull. Environ. Contam. Toxicol.")
    ("Bulletin for the History of Chemistry"	"Bull. Hist. Chem.")
    ("Bulletin of the Korean Chemical Society"	"Bull. Korean Chem. Soc.")
    ("Bulletin of Materials Science"		"Bull. Mater. Sci.")
    ("Bulletin of the Polish Academy of Sciences Chemistry" "Bull. Pol. Acad. Sci., Chem.")
    ("Bulletin des Societes Chimiques Belges"	"Bull. Soc. Chim. Belg.")
    ("Bulletin de la Societe Chimique de France" "Bull. Soc. Chim. Fr.")))
