(in-package :bib)

(appendf *abbrev-list*
  '(("Comptes Rendus de l' Academie des Sciences Serie III" "C.R. Acad. Sci., Ser. III")
    ("Comptes Rendus de l' Academie des Sciences Serie IIa" "C.R. Acad. Sci., Ser. IIa")
    ("Comptes Rendus de l' Academie des Sciences Serie IIb" "C.R. Acad. Sci., Ser. IIb")
    ("Comptes Rendus de l' Academie des Sciences Serie IIc" "C.R. Acad. Sci., Ser. IIc")
    ("Cahiers d'Informations Techniques / Revue de Metallurgie" "Cah. Inf. Tech./Rev Metall")
    ("Canadian Ceramics Quarterly"		"Can. Ceram. Q.")
    ("Canadian Journal of Analytical Sciences and Spectroscopy"	"Can. J. Anal. Sci. Spectros.")
    ("Canadian Journal of Biochemistry"		"Can. J. Biochem.")
    ("Canadian Journal of Chemistry"		"Can. J. Chem.")
    ("Canadian Journal of Chemical Engineering" "Can. J. Chem. Eng.")
    ("Canadian Journal of Microbiology"		"Can. J. Microbiol.")
    ("Canadian Journal of Physics"		"Can. J. Phys.")
    ("Canadian Journal of Physiology and Pharmacology" "Can. J. Physiol. Pharmacol.")
    ("Canadian Metallurgical Quarterly"		"Can. Metall. Q.")
    ("Canadian Mining Journal"			"Can. Min. J.")
    ("Canadian Mineralogist"			"Can. Mineral.")
    ("Carbohydrate Chemistry"			"Carbohydr. Chem.")
    ("Carbohydrate Letters"			"Carbohydr. Lett.")
    ("Carbohydrate Polymers"			"Carbohydr. Polym.")
    ("Carbohydrate Research"			"Carbohydr. Res.")
    ("Catalysis Reviews - Science and Engineering" "Cat. Rev. - Sci. Eng.")
    ("Catalysis Communications"			"Catal. Commun.")
    ("Catalysis Letters"			"Catal. Lett.")
    ("Catalysis Today"				"Catal. Today")
    ("Cell Biochemistry and Function"		"Cell Biochem. Funct.")
    ("Cellular Physiology and Biochemistry"	"Cell. Physiol. Biochem.")
    ("Cellular Polymers"			"Cell. Polym.")
    ("Cellulose Chemistry and Technology"	"Cellul. Chem. Technol.")
    ("Cement and Concrete Composites"		"Cem. Concr. Compos.")
    ("Cement and Concrete Research"		"Cem. Concr. Res.")
    ("Ceramics International"			"Ceram. Int.")
    ("Ceramics - Silikaty"			"Ceram. Silik.")
    ("Ceramic Transactions"			"Ceram. Trans.")
    ("Cereal Chemistry"				"Cereal Chem.")
    ("Chemie Anlagen und Verfahren"		"Chem. -Anlagen Verfahren")
    ("Chemia Analityczna"			"Chem. Anal. (Warsaw)")
    ("Chemistry in Australia"			"Chem. Aust.")
    ("Chemische Berichte"			"Chem. Ber.")
    ("Chemische Berichte-Recueil"		"Chem. Ber. Recl.")
    ("Chemical and Biochemical Engineering Quarterly" "Chem. Biochem. Eng. Q.")
    ("Chemico-Biological Interactions"		"Chem. Biol. Interact.")
    ("Chemistry in Britain"			"Chem. Br.")
    ("Chemical Communications"			"Chem. Commun.")
    ("Chemical Engineer (London)"		"Chem. Eng. (London)")
    ("Chemical Engineering (New York)"		"Chem. Eng. (New York)")
    ("Chemical Engineering Communications"	"Chem. Eng. Commun.")
    ("Chemical Engineering Journal"		"Chem. Eng. J.")
    ("News Chemical and Engineering News"	"Chem. Eng.")
    ("Chemical Engineering and Processing"	"Chem. Eng. Process.")
    ("Chemical Engineering Progress"		"Chem. Eng. Prog.")
    ("Chemical Engineering Research and Design" "Chem. Eng. Res. Des.")
    ("Chemical Engineering Science"		"Chem. Eng. Sci.")
    ("Chemical Engineering and Technology"	"Chem. Eng. Technol.")
    ("Chemistry- A European Journal"		"Chem. Eur. J.")
    ("Chemistry Express"			"Chem. Express")
    ("Chemical Fibers International"		"Chem. Fibers Int.")
    ("Chemistry A European Journal"		"Chem. Eur. J.")
    ("Chemical Geology"				"Chem. Geol.")
    ("Chemistry of Heterocyclic Compounds"	"Chem. Heterocycl. Compd.")
    ("Chemistry and Industry"			"Chem. Ind. (london)")
    ("Chemie Ingenieur Technik"			"Chem. Ing. Tech.")
    ("Chemistry Letters"			"Chem. Lett.")
    ("Chemicke Listy"				"Chem. Listy")
    ("Chemistry of Materials"			"Chem. Mater.")
    ("Chemistry of Natural Compounds"		"Chem. Nat. Compd.")
    ("Chemical Papers - Chemicke Zvesti"	"Chem. Pap. - Chem. Zvesti")
    ("Chemical and Pharmaceutical Bulletin"	"Chem. Pharm. Bull.")
    ("Chemical Physics"				"Chem. Phys.")
    ("Chemistry and Physics of Carbon"		"Chem. Phys. Carbon")
    ("Chemical Physics Letters"			"Chem. Phys. Lett.")
    ("Chemistry and Physics of Lipids"		"Chem. Phys. Lipids")
    ("Chemical Processing"			"Chem. Process.")
    ("Chemical Research in Toxicology"		"Chem. Res. Toxicol.")
    ("Chemical Reviews"				"Chem. Rev.")
    ("Chemical Senses"				"Chem. Senses")
    ("Chemical Society Reviews"			"Chem. Soc. Rev.")
    ("Chemical Speciation and Bioavailability"	"Chem. Speciation Bioavailability")
    ("ChemTech"					"Chem. Tech.")
    ("Chemische Technik"			"Chem. Tech. (Leipzig)")
    ("Chemistry and Technology of Fuels and Oils" "Chem. Technol. Fuels Oils")
    ("Chemical Vapor Deposition"		"Chem. Vap. Deposition")
    ("Chemical Week"				"Chem. Week")
    ("Chemie in unserer Zeit"			"Chem. unserer Zeit")
    ("Chemometrics and Intelligent Laborary Systems" "Chemom. Intell. Lab. Syst.")
    ("Chinese Chemical Letters"			"Chin. Chem. Lett.")
    ("Chinese Journal of Chemistry"		"Chin. J. Chem.")
    ("Chinese Journal of Chemical Engineering"	"Chin. J. Chem. Eng.")
    ("Chinese Journal of Nuclear Physics"	"Chin. J. Nucl. Phys.")
    ("Chinese Journal of Polymer Science"	"Chin. J. Polym. Sci.")
    ("Chinese Physics"				"Chin. Phys.")
    ("Chinese Physics B"			"Chin. Phys. B")
    ("Chinese Physics C"			"Chin. Phys. C")
    ("Chinese Physics Letters"			"Chin. Phys. Lett.")
    ("Chinese Science Bulletin"			"Chin. Sci. Bull.")
    ("Chromatographic Science Series"		"Chromatogr. Sci. Ser.")
    ("CIM Bulletin"				"CIM Bull.")
    ("Clays and Clay Minerals"			"Clays Clay Miner.")
    ("Clinical Biochemistry"			"Clin. Biochem.")
    ("Clinical Chemistry"			"Clin. Chem.")
    ("Clinica Chimica Acta"			"Clin. Chim. Acta")
    ("Clinical and Experimental Pharmacology and Physiology" "Clin. Exp. Pharmacol. Physiol.")
    ("Collection of Czechoslovak Chemical Communications" "Collect. Czech. Chem. Commun.")
    ("Colloid Journal"				"Colloid J.")
    ("Colloid and Polymer Science"		"Colloid. Polym. Sci.")
    ("Colloids and Surfaces A"			"Colloids Surf., A")
    ("Colloids and Surfaces B"			"Colloids Surf., B")
    ("Combinatorial Chemistry and High Throughput Screening" "Comb. Chem. High Throughput Screening")
    ("Combustion and Flame"			"Combust. Flame")
    ("Combustion Science and Technology"	"Combust. Sci. Technol.")
    ("Comments on Inorganic Chemistry"		"Comments Inorg. Chem.")
    ("Comparative Biochemistry and Physiology A" "Comp. Biochem. Physiol. A")
    ("Comparative Biochemistry and Physiology B" "Comp. Biochem. Physiol. B")
    ("Comparative Biochemistry and Physiology C" "Comp. Biochem. Physiol. C")
    ("Composites Engineering"			"Compos. Eng.")
    ("Composite Interfaces"			"Compos. Interfaces")
    ("Composites Science and Technology"	"Compos. Sci. Technol.")
    ("Composite Structures"			"Compos. Struct.")
    ("Composites Part A" 			"Composites Part A")
    ("Composites Part B"			"Composites Part B")
    ("Computers and Chemistry"			"Comput. Chem. (Oxford)")
    ("Computers and Chemical Engineering"	"Comput. Chem. Eng.")
    ("Computation Materials Science"		"Comput. Mater. Sci.")
    ("Computer Physics Communications"		"Comput. Phys. Commun.")
    ("Computational and Theoretical Polymer Science" "Comput. Theor. Polym. Sci.")
    ("Concepts in Magenetic Resonance"		"Concepts Magn. Reson.")
    ("Concrete Engineering International"	"Concr. Eng. Int.")
    ("Concrete International"			"Concr. Int.")
    ("Concrete Science and Engineering"		"Concr. Sci. Eng.")
    ("Condensed Matter Physics"			"Condens. Matter Phys.")
    ("Condensed Matter Theories"		"Condens. Matter Theor.")
    ("Continuum Mechanics and Thermodynamics"	"Continuum Mech. Thermodyn.")
    ("Contributions to Mineralogy and Petrology" "Contrib. Mineral. Petrol.")
    ("Coordination Chemistry Reviews"		"Coord. Chem. Rev.")
    ("Corrosion Reviews"			"Corros. Rev.")
    ("Corrosion Science"			"Corros. Sci.")
    ("CPP Chemical Plants and Processing"	"CPP Chem. Plants and Process.")
    ("Critical Reviews in Analytical Chemistry" "Crit. Rev. Anal. Chem.")
    ("Critical Reviews in Biochemistry and Molecular Biology" "Crit. Rev. Biochem. Mol. Biol.")
    ("Critical Reviews in Biotechnology"	"Crit. Rev. Biotechnol.")
    ("Critical Reviews in Environment Science and Technology" "Crit. Rev. Env. Sci. Technol.")
    ("Critical Reviews in Solid State and Materials Sciences" "Crit. Rev. Solid State Mater. Sci.")
    ("Critical Reviews in Toxicology"		"Crit. Rev. Toxicol.")
    ("Croatica Chemica Acta"			"Croat. Chem. Acta")
    ("Crystal Engineering"			"Cryst. Eng.")
    ("Crystal Growth and Design"		"Cryst. Growth Des.")
    ("Crystal Research and Technology"		"Cryst. Res. Technol.")
    ("Current Opinion in Biotechnology"		"Curr. Opin. Biotechnol.")
    ("Current Opinion in Chemical Biology"	"Curr. Opin. Chem. Biol.")
    ("Current Opinion in Colloid and Interface Science" "Curr. Opin. Colloid Interface Sci.")
    ("Current Opinion in Pharmacology"		"Curr. Opin. Pharmacol.")
    ("Current Opinion in Solid State and Materials Science" "Curr. Opin. Solid State Mater. Sci.")
    ("Current Organic Chemistry"		"Curr. Org. Chem.")
    ("Current Plant Science in Biotechnology and Agriculture" "Curr. Plant Sci. Biotechnol. Agric.")
    ("Current Topics in Membranes"		"Curr. Top. Membr.")
    ("Current Topics in Medicinal Chemistry"	"Curr. Top. Med. Chem.")))
