(in-package :bib)

(appendf *abbrev-list*
  '(("Earth and Planetary Science Letters"	"Earth. Planet. Sci. Lett.")
    ("Ecological Engineering"			"Ecol. Eng.")
    ("Ecotoxicology and Environment Safety"	"Ecotoxicol. Environ. Saf.")
    ("Education in Chemistry"			"Educ. Chem.")
    ("Electro- and Magnetobiology"		"Electro- Magnetobiol.")
    ("Electrochemistry Communications"		"Electrochem. Commun.")
    ("Electrochemical Society Interface"	"Electrochem. Soc. Interface")
    ("Electrochemical and Solid-State Letters"	"Electrochem. Solid-State Lett.")
    ("Electrochimica Acta"			"Electrochim. Acta")
    ("Electronics Letters"			"Electron. Lett")
    ("Electronic Technology"			"Electron Technol.")
    ("EMBO Journal"				"EMBO J.")
    ("Energy Conversion and Management"		"Energy Convers. Manage.")
    ("Energy and Fuels"				"Energy Fuels")
    ("Engineering and Mining Journal"		"Eng. Min. J.")
    ("Environment Carcinogenesis and Ecotoxicology Reviews" "Environ. Carcinog. Ecotoxicol. Rev.")
    ("Environmental Geochemistry and Health"	"Environ. Geochem. Health")
    ("Environmental Geology"			"Environ. Geol.")
    ("Environmental Health Perspectives"	"Environ. Health Perspect.")
    ("Environmental Microbiology"		"Environ. Microbiol.")
    ("Environmental Monitoring and Assessment"	"Environ. Monit. Assess.")
    ("Environmental Pollution"			"Environ. Pollut.")
    ("Environmental Progress"			"Environ. Prog.")
    ("Environmental Research"			"Environ. Res.")
    ("Environmental Science and Technology"	"Environ. Sci. Technol.")
    ("Environmental Technology"			"Environ. Technol.")
    ("Environmental Toxicology and Chemistry"	"Environ. Toxicol. Chem.")
    ("Environmental Toxicology and Pharmacology" "Environ. Toxicol. Pharmacol.")
    ("Environmental Toxicology and Water Quality" "Environ. Toxicol. Water Qual.")
    ("Enzyme and Microbial Technology"		"Enzyme Microb. Technol.")
    ("Enzyme and Protein"			"Enzyme Protein")
    ("Erdol and Kohle Erdgas, Petrochemie"	"Erdol and Kohle Erdgas, Petrochem.")
    ("European Journal of Biochemistry"		"Eur. J. Biochem.")
    ("European Journal of Clinical Chemistry and Clinical Biochemistry" "Eur. J. Clin. Chem. Clin. Biochem.")
    ("European Journal of Inorganic Chemistry"	"Eur. J. Inorg. Chem.")
    ("European Journal of Lipid Science and Technology" "Eur. J. Lipid Sci. Technol.")
    ("European Journal of Mass Spectrometry"	"Eur. J. Mass Spectrom.")
    ("European Journal of Medical Chemistry"	"Eur. J. Med. Chem.")
    ("European Journal of Mineralogy"		"Eur. J. Mineral.")
    ("European Journal of Organic Chemistry"	"Eur. J. Org. Chem.")
    ("European Journal of Pharmacology"		"Eur. J. Pharmacol.")
    ("European Journal of Solid State and Inorganic Chemistry" "Eur. J. Solid State Inorg. Chem.")
    ("European Mass Spectrometry"		"Eur. Mass Spectrom.")
    ("European Polymer Journal"			"Eur. Polym. J.")
    ("Europhysics Letters"			"Europhys. Lett.")
    ("Experiments in Fluids"			"Exp. Fluids")
    ("Experimental Thermal and Fluid Science"	"Exp. Therm Fluid Sci.")
    ("Expert Opinion on Pharmacotherapy"	"Expert Opin. Pharmacother.")
    ("Exploration and Mining Geology"		"Explor. Min. Geol.")))
