(in-package :bib)

(appendf *abbrev-list*
  '(("Faraday Discussions"			"Faraday Discuss.")
    ("FASEB Journal"				"FASEB J.")
    ("Fatigue and Fracture of Engineering Materials and Structures" "Fatigue Fract. Eng. Mater. Struct.")
    ("FEBS Letters"				"FEBS Lett.")
    ("FEMS Immunology And Medical Microbiology" "FEMS Immunol. Med. Microbiol.")
    ("FEMS Microbiology Ecology"		"FEMS Microbiol. Ecol.")
    ("FEMS Microbiology Letters"		"FEMS Microbiol. Lett.")
    ("FEMS Microbiology Review"			"FEMS Microbiol. Rev.")
    ("Ferroelectrics Review"			"Ferroelectr. Rev.")
    ("Ferroelectrics Letters"			"Ferroelectr. Lett.")
    ("Fett - Lipid"				"Fett - Lipid")
    ("Fiber and Integrated Optics"		"Fiber Integr. Opt.")
    ("Field Analytical Chemistry and Technology." "Field Anal. Chem. Technol.")
    ("Filtration and Separation"		"Filtr. Sep.")
    ("Fizika Metallov i Metallovedenie"		"Fiz. Met. Metalloved.")
    ("Fluid/Particle Separation Journal"	"Fluid/Part. Sep. J.")
    ("Fluid Phase Equilibria"			"Fluid Phase Equilib.")
    ("Folding and Design"			"Fold Des.")
    ("Food Additives and Contaminants"		"Food Addit. Contam.")
    ("Food Biotechnology"			"Food Biotechnol.")
    ("Food Chemistry"				"Food Chem.")
    ("Food and Chemical Toxicology"		"Food Chem. Toxicol.")
    ("Food Science and Technology International" "Food Sci. Technol. Int.")
    ("Free Radical Biology and Medicine"	"Free Radical Biol. Med.")
    ("Free Radical Research"			"Free Radical Res.")
    ("Fresenius Environment bulletin"		"Fresenius Environ. Bull.")
    ("Fresenius Journal of Analytical Chemistry" "Fresenius J. Anal. Chem.")
    ("Frontiers of Physics" 			"Front. Phys.")
    ("Frontier Science Series"			"Front Sci. Ser.")
    ("Fuel Processing Technology"		"Fuel Process. Technol.")
    ("Fuel Science and Technology International" "Fuel Sci. Technol. Int.")
    ("Fullerene Science and Technology"		"Fullerene Sci. Technol.")
    ("Functional and Integrative Genomics"	"Funct. Integr. Genomics")
    ("Fundamental and Applied Toxicology"	"Fundam. Appl. Toxicol.")
    ("Fusion Engineering and Design"		"Fusion Eng. Des.")
    ("Fusion Technology"			"Fusion Technol.")))
