(in-package :bib)

(appendf *abbrev-list*
  '(("Galvanotechnik"				"Galvanotechnik")
    ("Gas Separation and Purification"		"Gas Sep. Purif.")
    ("Gazzetta Chimica Italiana"		"Gazz. Chim. Ital.")
    ("Gefahrstoffe Reinhaltung der Luft"	"Gefahrstoffe - Reinhalt. Luft")
    ("Genetic Analysis - Biomolecular Engineering" "Genet. Anal. - Biomol. Eng.")
    ("Geochemistry, Geophysics, Geosystems"	"Geochem. Geophys. Geosyst.")
    ("Geochemical Journal"			"Geochem. J.")
    ("Geochemical Transactiosn"			"Geochem. Trans.")
    ("Geochemistry: Exploration, Environment, Analysis" "Geochem.: Explor. Environ., Anal.")
    ("Geochimica et Cosmochimica Acta"		"Geochim. Cosmochim. Acta")
    ("Geologiya i Geofizika"			"Geol Geofiz")
    ("Geomicrobiology Journal"			"Geomicrobiol. J.")
    ("Glass and Ceramics"			"Glass Ceram.")
    ("Glass Physics and Chemistry"		"Glass Phys. Chem.")
    ("Glass Research"				"Glass Res.")
    ("Glass Science and Technology"		"Glass Sci. Technol.")
    ("Glass Technology"				"Glass Technol.")
    ("Global Biogeochemical Cycles"		"Global Biogeochem. Cycles")
    ("Global Journal of Pure and Applied Sciences" "Global J. Pure Appl. Sci.")
    ("Glycoconjugate Journal"			"Glycoconjugate J.")
    ("Greem Chemistry"				"Green Chem.")
    ("Ground Water Monitoring and Remediation"	"Ground Water Monit. Rem.")))
