(in-package :bib)

(appendf *abbrev-list*
  '(("Handbook of Experimental Pharmacology" 	"Handb. Exp. Pharmacol.")
    ("Hazardous Waste and Hazardous Materials"  "Hazard. Waste Hazard. Mater.")
    ("HeIvetica Chimica Acta"			"HeIv. Chim. Acta")
    ("Health Physics"				"Health Phys.")
    ("Heat and Mass Transfer"			"Heat Mass Transfer.")
    ("Heat Treatment of Metals"			"Heat Treat. Met.")
    ("Heteroatom Chemistry"			"Heteroat. Chem")
    ("Heterocyclic Communications"		"Heterocycl. Commun.")
    ("Heterogeneous Chemistry Reviews"		"Heterogen. Chem. Rev.")
    ("High Energy Chemistry"			"High Energ. Chem.")
    ("High Performance Polymers"		"High Perform. Polym.")
    ("High Temperature Materials and Processes" "High Temp. Mater. Processes (London)")
    ("High Temperature Material Processes"	"High Temp. Mater. Processes (New York)")
    ("Holz als Roh und Werkstoff"		"Holz Roh Werkst.")
    ("Hoppe-Seyler's Zeitschrift fur Physiologische Chemie" "Hoppe-Seyler's Z. Physiol. Chem.")
    ("HRC Journal of High Resolution Chromatography" "HRC J. High Resolut. Chromatogr.")
    ("Hungarian Journal of Industrial Chemistry" "Hung. J. Ind. Chem.")
    ("Hydrocarbon Processing, International Edition" "Hydrocarbon Process., Int. Ed.")
    ("Hyperfine Interactions"			"Hyperfine Interact.")))
