(in-package :bib)

(appendf *abbrev-list*
  '(("IEEE Sensors Journal"			"IEEE Sens. J.")
    ("Industrial Diamond Review"		"Ind. Diamond Rev.")
    ("Industrial and Engineering Chemistry Research Fundamentals" "Ind. Eng. Chem. Fundam.")
    ("Industrial and Engineering Chemistry Research" "Ind. Eng. Chem. Res.")
    ("Indian Journal of Biochemistry and Biophysics" "Indian J. Biochem. Biophys.")
    ("Indian Journal of Chemical Technology"	"Indian J. Chem. Technol.")
    ("Indian Journal of Chemistry Section A" "Indian J. Chem., Sect A")
    ("Indian Journal of Chemistry Section B" "Indian J. Chem., Sect B")
    ("Indian Journal of Engineering and Materials Science" "Indian J. Eng. Mater. Sci.")
    ("Indian Journal of Heterocyclic Chemistry" "Indian J. Heterocycl. Chem.")
    ("Indian Journal of Pure and Applied Physics" "Indian J. Pure Appl. Phys.")
    ("Indian Journal of Technology"		"Indian J. Technol.")
    ("Ingeniera Quimica (Madrid)"		"Ing. Quim.")
    ("Infrared Physics and Technology"		"Infrared Phys. Technol.")
    ("Inorganic Chemistry"			"Inorg. Chem.")
    ("Inorganic Chemistry Communications"	"Inorg. Chem. Commun.")
    ("Inorganica Chimica Acta"			"Inorg. Chim. Acta")
    ("Inorganic Materials"			"Inorg. Mater.")
    ("Inorganic Reaction Mechanisms"		"Inorg. React. Mech.")
    ("Inorganic Syntheses"			"Inorg. Synth.")
    ("Insect Biochemisry and Molecular Biology" "Insect Biochem. Mol. Biol.")
    ("Instrumentation Science and Technology"	"Instrum Sci. Technol.")
    ("International Biodeterioration and Biodegradation" "Int. Biodeterior. Biodegrad.")
    ("International DATA Series, Selected Data on Mixtures, Series A" "Int. DATA Ser., Sel. Data Mixtures, Ser. A")
    ("International Journal of Adhesion and Adhesives" "Int. J. Adhes. Adhes.")
    ("International Journal of Biochemistry"	"Int. J. Biochem.")
    ("International Journal of Biochemistry and Cell Biology" "Int. J. Biochem. Cell Biol.")
    ("International Journal of Biochromatography" "Int. J. Bio-Chromatogr.")
    ("International Journal of Biological Macromolecules" "Int. J. Biol. Macromol.")
    ("International Journal of Cast Metals Research" "Int. J. Cast Met. Res.")
    ("International Journal of Chemical Kinetics" "Int. J. Chem. Kinet.")
    ("International Journal of Environment Analytical Chemistry" "Int. J. Environ. Anal. Chem.")
    ("International Journal of Fatigue"		"Int. J. Fatigue")
    ("International Journal of heat and fluid flow" "Int. J. Heat Fluid Flow")
    ("International Journal of Heat and Mass Transfer" "Int. J. Heat Mass Transfer")
    ("International Journal of Hydrogen Energy"	"Int. J. Hydrogen Energy")
    ("International Journal of Immunopharmacology" "Int. J. Immunopharmacol")
    ("International Journal of Inorganic Materials" "Int. J. Inorg. Mater.")
    ("International Journal of Mass Spectrometry"	"Int. J. Mass spectrom.")
    ("International Journal of Mass Spectrometry and Ion Processes" "Int. J. Mass Spectrom. Ion Processes")
    ("International Journal of Mineral Processing"	"Int. J. Miner. Process.")
    ("International Journal of Modern Physics B"	"Int. J. Mod Phys B")
    ("International Journal of Multiphase Flow"		"Int. J. Multiphase Flow")
    ("International Journal of Nuclear Energy"		"Int. J. Nucl. Energy")
    ("International Journal for Numerical Methods in Fluids" "Int. J. Numer. Methods Fluids")
    ("International Journal of Oncology"		"Int. J. Oncol.")
    ("International Journal of Peptide and Protein Research" "Int. J. Pept. Protein Res.")
    ("International Journal of Pharmaceutics"		"Int. J. Pharm.")
    ("International Journal of Phytoremediation"	"Int. J. Phytorem.")
    ("International Journal of Plasticity"		"Int. J. Plast.")
    ("International Journal of Polymer Analysis and Characterization" "Int. J. Polym. Anal. Charact.")
    ("International Journal of Polymeric Materials"	"Int. J. Polymer. Mater.")
    ("International Journal of Powder Metallurgy"	"Int. J. Powder Metall.")
    ("International Journal of Quantum Chemistry"	"Int. J. Quantum Chem.")
    ("International Journal of Radiation Biology"	"Int. J. Radiat Biol.")
    ("International Journal of Refractory Metals and Hard Materials" "Int. J. Refract. Met. Hard Mater.")
    ("International Journal of Self-Propagating High-Temperature Synthesis" "Int. J. Self-Propag. High-Temp Synth.")
    ("International Journal of Thermophysics"		"Int. J. Thermophys.")
    ("International Materials Reviews"			"Int. Mater. Rev.")
    ("International Polymer Processing"			"Int. Polym. Proc.")
    ("International Reviews in Physical Chemistry"	"Int. Rev. Phys. Chem.")
    ("Interface Science"				"Interface Sci.")
    ("Internet Journal of Vibrational Spectroscopy"	"Internet J. Vib. Spectro.")
    ("Internet Journal of Chemistry"			"Int. J. Thermophys.")
    ("Inzynieria Chemiczna i Procesowa"			"Inz. Chem. Procesowa")
    ("Ironmaking and Steelmaking"			"Ironmaking Steelmaking")
    ("ISIJ International"				"ISIJ Int.")
    ("Israel Journal of Chemistry"			"Isr. J. Chem.")))
