(in-package :bib)

(appendf *abbrev-list*
  '(("Journal of Adhesion"				"J. Adhes.")
    ("Journal of Adhesion Science and Technology" 	"J. Adhes. Sci. Technol.")
    ("Journal of Advanced Materials"			"J. Adv. Mater.")
    ("Journal of Aerosol Science"			"J. Aerosol Sci.")
    ("Journal of Agricultural and Food Chemistry"	"J. Agric. Food. Chem.")
    ("Journal of the Air and Waste Management Association" "J. Air Waste Manage. Assoc.")
    ("Journal of Alloys and Compounds"			"J. Alloys Compd.")
    ("Journal of the American Ceramic Society"		"J. Am. Ceram. Soc.")
    ("Journal of the American Chemical Society"		"J. Am. Chem. Soc.")
    ("Journal of the American Oil Chemists Society"	"J. Am. Oil Chem. Soc.")
    ("Journal of the American Society of Brewing Chemists" "J. Am. Soc. Brew. Chem.")
    ("Journal of the American Society for Mass Spectrometry" "J. Am. Soc. Mass. Spectrom.")
    ("Journal of the American Chemical Society"		"J. Amer. Chem. Soc.")
    ("Journal of Analytical and Applied Pyrolysis" 	"J. Anal. Appl. Pyrolysis")
    ("Journal of Analytical Atomic Spectrometry"	"J. Anal. At. Spectrom.")
    ("Journal of Analytical Chemistry"			"J. Anal. Chem.")
    ("Journal of Analytical Toxicology"			"J. Anal. Toxicol.")
    ("Journal of Antibiotics"				"J. Antibiot.")
    ("Journal of Antimicrobial Chemotherapy"		"J. Antimicrob. Chemother.")
    ("Journal of AOAC International"			"J. AOAC Int.")
    ("Journal of Applied Bacteriology"			"J. Appl. Bacteriol.")
    ("Journal of Applied Biomaterials"			"J. Appl. Biomater.")
    ("Journal of Applied Crystallography"		"J. Appl. Crystallogr.")
    ("Journal of Applied Electrochemistry"		"J. Appl. Electrochem.")
    ("Journal of Applied Phycology"			"J. Appl. Phycol.")
    ("Journal of Applied Physics"			"J. Appl. Phys.")
    ("Journal of Applied Polymer Science"		"J. Appl. Polym. Sci.")
    ("Journal of Applied Spectroscopy"			"J. Appl. Spectrosc.")
    ("Journal of Applied Toxicology"			"J. Appl. Toxicol.")
    ("Journal of Asian Natural Products Research"	"J. Asian Nat. Prod. Res.")
    ("Journal of Automatic Chemistry"			"J. Autom. Chem.")
    ("Journal of Automated Methods & Management in Chemistry" "J. Autom. Methods Manage. Chem.")
    ("Journal of Bacteriology"				"J. Bacteriol.")
    ("Journal of Bioactive and Bompatible Polymers"	"J. Bioact. Compat. Polym.")
    ("Journal of Biochemistry"				"J. Biochem.")
    ("Journal of Biochemical and Biophysical Methods"	"J. Biochem. Bioph. Methods")
    ("Journal of Biological Chemistry"			"J. Biol. Chem.")
    ("Journal of Biological Inorganic Chemistry"	"J. Biol. Inorg. Chem.")
    ("Journal of Bioluminescence and Chemiluminescence"	"J. Biolumin. Chemilumin.")
    ("Journal of Biomaterials Applications"		"J. Biomater. Appl.")
    ("Journal of Biomaterials Science Polymer Edition"	"J. Biomater. Sci., Polym. Ed.")
    ("Journal of Biomedial Materials Research"		"J. Biomed. Mater. Res.")
    ("Journal of Biomolecular NMR"			"J. Biomol. NMR")
    ("Journal of Biomolecular Structure and Dynamics"	"J. Biomol. Struct. Dyn.")
    ("Journal of Biotechnology"				"J. Biotechnol.")
    ("Journal of Canadian Petroleum Technology"		"J. Can. Pet. Technol.")
    ("Journal of Carbohydrate Chemistry"		"J. Carbohydr. Chem.")
    ("Journal of Cardiovascular Pharmacology"		"J. Cardiovasc. Pharmacol.")
    ("Journal of Catalysis"				"J. Catal.")
    ("Journal of Cellular Biochemistry"			"J. Cell. Biochem.")
    ("Journal of Cell Biology"				"J. Cell Biol.")
    ("Journal of Cellular Physiology"			"J. Cell. Physiol.")
    ("Journal of Cell Science"				"J. Cell Sci.")
    ("Journal of the Ceramic Society of Japan"		"J. Ceram. Soc. Jpn.")
    ("Journal of Chemical Crystallography"		"J. Chem. Crystallogr.")
    ("Journal of Chemical Ecology"			"J. Chem. Ecol.")
    ("Journal of Chemical Education"			"J. Chem. Educ.")
    ("Journal of Chemical and Engineering Data"		"J. Chem. Eng. Data")
    ("Journal of Chemical Engineering of Japan"		"J. Chem. Eng. Jpn.")
    ("Journal of Chemical Information and Computer Science" "J. Chem. Inf. Comput. Sci.")
    ("Journal of Chemical Neuroanatomy"			"J. Chem. Neuroanat.")
    ("Journal of Chemical Research Synopsis"		"J. Chem. Res., Synop.")
    ("Journal of the Chemical Society"			"J. Chem. Soc.")
    ("Journal of the Chemical Society of Pakistan"	"J. Chem. Soc. Pak.")
    ("Journal of the Chemical Society, Chemical Communications" "J. Chem. Soc., Chem. Commun.")
    ("Journal of the Chemical Society, Dalton Transactions" "J. Chem. Soc., Dalton Trans.")
    ("Journal of the Chemical Society, Faraday Transactions" "J. Chem. Soc., Faraday Trans.")
    ("Journal of the Chemical Society, Perkin Transactions 1" "J. Chem. Soc., Perkin Trans. 1")
    ("Journal of the Chemical Society, Perkin Transactions 2" "J. Chem. Soc., Perkin Trans. 2")
    ("Journal of Chemical Technology and Biotechnology"	"J. Chem. Technol. Biotechnol.")
    ("Journal of Chemical Thermodynamics"		"J. Chem. Thermodyn.")
    ("Journal of Chemometrics"				"J. Chemom.")
    ("Journal de Chimie Physique et de Physico-Chimie Biologique" "J. Chim. Phys. Phys.-Chim. Biol.")
    ("Journal of the Chinese Chemical Society"		"J. Chin. Chem. Soc.")
    ("Journal of the Chinese Institute of Chemical Engineers" "J. Chin. Inst. Chem. Eng.")
    ("Journal of Chromatography"			"J. Chromatogr.")
    ("Journal of Chromatography A"			"J. Chromatogr. A")
    ("Journal of Chromatography B"			"J. Chromatogr. B")
    ("Journal of Chromatographic Science"		"J. Chromatogr. Sci.")
    ("Journal of Clinical Endocrinology and Metabolism" "J. Clin. Endocrinol. Metab.")
    ("Journal of Clinical Microbiology"			"J. Clin. Microbiol.")
    ("Journal of Cluster Science"			"J. Cluster Sci.")
    ("Journal of Coatings Technology"			"J. Coat. Technol.")
    ("Journal of Colloid and Interface Science"		"J. Colloid Interface Sci.")
    ("Journal of Combinatorial Chemistry"		"J. Comb. Chem.")
    ("Journal of Composite Materials"			"J. Compos. Mater.")
    ("Journal of Composites Technology and Research"	"J. Compos. Tech. Res.")
    ("Journal of Computer-Aided Materials Design"	"J. Comput. Aided Mater. Des.")
    ("Journal of Computer-Aided Molecular Design"	"J. Comput. Aided Mol. Des.")
    ("Journal of Computational Chemistry"		"J. Comput. Chem.")
    ("Journal of Contaminant Hydrology"			"J. Contam. Hydrol.")
    ("Journal of Controlled Release"			"J. Controlled Release")
    ("Journal of Coordination Chemistry"		"J. Coord. Chem.")
    ("Journal of Crystal Growth"			"J. Cryst. Growth")
    ("Journal of Dairy Science"				"J. Dairy Sci.")
    ("Journal of Dispersion Science and Technology"	"J. Dispersion Sci. Technol.")
    ("Journal of Elastomers and Plastics"		"J. Elastomers Plast.")
    ("Journal of Electroanalytical Chemistry"		"J. Electroanal. Chem.")
    ("Journal of Electroceramics"			"J. Electroceram.")
    ("Journal of the Electrochemical Society"		"J. Electrochem. Soc.")
    ("Journal of Electronic Materials"			"J. Electron. Mater.")
    ("Journal of Electron Microscopy"			"J. Electron Microsc.")
    ("Journal of Electron Spectroscopy and Related Phenomena" "J. Electron. Spectrosc. Relat. Phenom.")
    ("Journal of Endocrinology"				"J. Endocrinol.")
    ("Journal of Endotoxin Research"			"J. Endotoxin Res.")
    ("Journal of Engineering Materials and Technology"	"J. Eng. Mater. Technol.")
    ("Journal of Environmental Biology"			"J. Environ. Biol.")    
    ("Journal of Environmental Engineering"		"J. Environ. Eng.")
    ("Journal of Environmental Health"			"J. Environ. Health")
    ("Journal of Environmental Management"		"J. Environ. Manage.")
    ("Journal of Environmental Monitoring"		"J. Environ. Monit.")
    ("Journal of Environmental Quality"			"J. Environ. Qual.")
    ("Journal of Environmental Radioactivity"		"J. Environ. Radioact.")
    ("Journal of Environmental Science and Health, Part A" "J. Environ. Sci. Health., Part A")
    ("Journal of Environmental Science and Health, Part B Pesticides" "J. Environ. Sci. Health., Part B")
    ("Journal of Enzyme Inhibition"			"J. Enzym Inhib.")
    ("Journal of Essential Oil Research"		"J. Essent. Oil Res.")
    ("Journal of Ethnopharmacology"			"J. Ethnopharmacol.")
    ("Journal of the European Ceramic Society"		"J. Eur. Ceram. Soc.")
    ("Journal of Experimental Biology"			"J. Exp. Biol.")
    ("Journal of Experimental Botany"			"J. Exp. Bot.")
    ("Journal of Exposure Analysis and Environment Epidemiology" "J. Exposure Anal. Environ. Epidemiol.")
    ("Journal of Fermentation and Bioengineering"	"J. Ferment. Bioeng.")
    ("Journal of Fire Sciences"				"J. Fire Sci.")
    ("Journal of Fluid Mechanics"			"J. Fluid Mech.")
    ("Journal of Fluids Engineering"			"J. Fluids Eng.")
    ("Journal of Fluorine Chemistry"			"J. Fluorine Chem.")
    ("Journal of Food Biochemistry"			"J. Food Biochem.")
    ("Journal of Food Engineering"			"J. Food Eng.")
    ("Journal of Food Lipids"				"J. Food Lipids")
    ("Journal of Food Protection"			"J. Food Prot.")
    ("Journal of Food Science"				"J. Food Sci.")
    ("Journal of General and Applied Microbiology"	"J. Gen. Appl. Microbiol.")
    ("Journal of General Microbiology"			"J. Gen. Microbiol.")
    ("Journal of Hazardous materials"			"J. Hazard. Mater.")
    ("Journal of Heat Transfer"				"J. Heat Transfer")
    ("Journal of Heterocyclic Chemistry"		"J. Heterocycl. Chem.")
    ("Journal of High Resolution Chromatography"	"J. High. Resolut. Chromatogr.")
    ("Journal of Histochemistry and Cytochemistry"	"J. Histochem. Cytochem.")
    ("Journal of Hypertension"				"J. Hypertens.")
    ("Journal of Imaging Science and Technology"	"J. Imaging Sci. Technol.")
    ("Journal of Inclusion Phenomena and Molecular Recognition in Chemistry" "J. Inclusion Phenom. Mol. Recognit. Chem.")
    ("Journal of Industrial Microbiology"		"J. Ind. Microbiol.")
    ("Journal of the Indian Chemical Society"		"J. Indian Chem. Soc.")
    ("Journal of Industrial Microbiology and Biotechnology" "J. Ind. Microbiol. Biotechnol.")
    ("Journal of Inorganic Biochemistry"		"J. Inorg. Biochem.")
    ("Journal of Inorganic and Nuclear Chemistry"	"J. Inorg. Nucl. Chem.")
    ("Journal of Inorganic and Organometallic Polymers"	"J. Inorg. Organomet. Polym.")
    ("Journal of Institute of Chemists (India)"		"J. Inst. Chem.")
    ("Journal of the Institute of Environment Sciences" "J. Inst. Environ. Sci.")
    ("Journal of the Institution of Water and Environment Management" "J. Inst. Water Environ. Manage.")
    ("Journal of Intelligent Material Systems and Structures" "J. Intell. Mater. Syst. Struct.")
    ("Journal of Interferon and Cytokine Research"	"J. Interferon Cytokine Res.")
    ("Journal of Interferon Research"			"J. Interferon Res.")
    ("Journal of the Japan Institute of Metals"		"J. Jpn. Inst. Met.")
    ("Journal of the Korean Chemical Society"		"J. Korean Chem. Soc.")
    ("Journal of Labelled Compounds and Radiopharmaceuticals" "J. Labelled Compd. Radiopharm.")
    ("Journal of Lipid Mediators"			"J. Intell. Mater. Syst. Struct.")
    ("Journal of Lipid Mediators and Cell Signalling"	"J. Lipid Mediators Cell Signalling")
    ("Journal of Lipid Research"			"J. Lipid Res.")
    ("Journal of Liquid Chromatography"			"J. Liq. Chromatogr.")
    ("Journal of Liquid Chromatography and Related Technologies" "J. Liq. Chromatogr. Related Technol.")
    ("Journal of Low Temperature Physics"		"J. Low Temp. Phys.")
    ("Journal of Luminescence"				"J. Lumin.")
    ("Journal of Macromolecular Science - Physics"	"J. Macromol. Sci., Phys.")
    ("Journal of Macromolecular Science Polymer Reviews" "J. Macromol. Sci., Polym. Rev.")
    ("Journal of Macromolecular Science Pure and Applied Chemistry" "J. Macromol. Sci., Pure Appl. Chem.")
    ("Journal of Macromolecular Science - Reviews in Macromolecular Chemistry and Physics" "J. Macromol. Sci., Rev. Macromol. Chem. Phys.")
    ("Journal of Magnetism and Magnetic Materials"	"J. Magn. Magn. Mater.")
    ("Journal of Magnetic Resonance Series A"		"J. Magn. Reson., Ser A")
    ("Journal of Magnetic Resonance Series B"		"J. Magn. Reson., Ser B")
    ("Journal of Mass Spectrometry"			"J. Mass Spectrom.")
    ("Journal of Materials Chemistry"			"J. Mater. Chem.")
    ("Journal of Materials in Civil Engineering"	"J. Mater. Civ. Eng.")
    ("Journal of Material Cycles and Waste Management"	"J. Mater. Cycles Waste Manage.")
    ("Journal of Materials Engineering and Performance" "J. Mater. Eng. Perform.")
    ("Journal of Materials Processing and Manufacturing Science" "J. Mater. Process. Manuf. Sci.")
    ("Journal of Materials Processing Technology"	"J. Mater. Process. Technol.")
    ("Journal of Materials Research"			"J. Mater. Res.")
    ("Journal of Materials Science"			"J. Mater. Sci.")
    ("Journal of Materials Science Letters"		"J. Mater. Sci. Lett.")
    ("Journal of Materials Science - Materials in Electronics" "J. Mater. Sci. - Mater. Electron.")
    ("Journal of Materials Science Materials in Medicine" "J. Mater. Sci. - Mater. Med.")
    ("Journal of Materials Science and Technology"	"J. Mater. Sci. Technol.")
    ("Journal of Materials Synthesis and Processing"	"J. Mater. Synth. Process.")
    ("Journal of Mathematical Chemistry"		"J. Math. Chem.")
    ("Journal of Mathematical Physics"			"J. Math. Phys.")
    ("Journal of Medicinal Chemistry"			"J. Med. Chem.")
    ("Journal of Membrane Biology"			"J. Membr. Biol.")
    ("Journal of Membrance Science"			"J. Membr. Sci.")
    ("Journal of Microbiology and Biotechnology"	"J. Microbiol. Biotechnol.")
    ("Journal of Microbiological Methods"		"J. Microbiol. Methods")
    ("Journal of Microcolumn Separations"		"J. Microcolumn Sep.")
    ("Journal of Microelectronic Systems"		"J. Microelectromech. Syst.")
    ("Journal of Microencapsulation"			"J. Microencapsulation")
    ("Journal of Molecular Biology"			"J. Mol. Biol.")
    ("Journal of Molecular Catalysis"			"J. Mol. Catal.")
    ("Journal of Molecular Catalysis A"			"J. Mol. Catal. A")
    ("Journal of Molecular Catalysis B"			"J. Mol. Catal. B")
    ("Journal of Molecular Graphics and Modelling"	"J. Mol. Graphics Modell.")
    ("Journal of Molecular Liquids"			"J. Mol. Liq.")
    ("Journal of Molecular Microbiology and Biotechnology" "J. Mol. Microbiol. Biotechnol.")
    ("Journal of Molecular Modeling"			"J. Mol. Model.")
    ("Journal of Molecular Spectroscopy"		"J. Mol. Spectrosc.")
    ("Journal of Molecular Structure"			"J. Mol. Struct.")
    ("Journal of Nanoparticle Research"			"J. Nanopart. Res.")
    ("Journal of Natural Products"			"J. Nat. Prod.")
    ("Journal of Near Infrared Spectroscopy"		"J. Near Infrared Spectrosc.")
    ("Journal of Neurochemistry"			"J. Neurochem.")
    ("Journal of Neuroscience"				"J. Neurosci.")
    ("Journal of Neuroscience Research"			"J. Neurosci. Res.")
    ("Journal of New Materials for Electrochemical Systems" "J. New Mater. Electrochem. Syst.")
    ("Journal of Non-Crystalline Solids"		"J. Non-Cryst. Solids")
    ("Journal of Non-Equilibrium Thermodynamics"	"J. Non-Equilib. Thermodyn.")
    ("Journal of Nuclear Materials"			"J. Nucl. Mater.")
    ("Journal of Nuclear Science and Technology"	"J. Nucl. Sci. Technol.")
    ("Journal of the Optical Society of America B"	"J. Opt. Soc. Am. B")
    ("Journal of Organic Chemistry"			"J. Org. Chem.")
    ("Journal of Organometallic Chemistry"		"J. Organomet. Chem.")
    ("Journal of Petroleum Science and Technology"	"J. Pet. Sci. Technol.")
    ("Journal of Pharmaceutical and Biomedical Analysis" "J. Pharm. Biomed. Anal.")
    ("Journal of Pharmacy and Pharmacology"		"J. Pharm. Pharmacol.")
    ("Journal of Pharmaceutical Sciences"		"J. Pharm. Sci.")
    ("Journal of Pharmacology and Experimental Therapeutics" "J. Pharmacol. Exp. Ther.")
    ("Journal of Pharmacological and Toxicological Methods" "J. Pharmacol. Toxicol. Methods")
    ("Journal of Phase Equilibrium"			"J. Phase Equilib.")
    ("Journal of Photochemistry and Photobiology A"	"J. Photochem. Photobiol., A")
    ("Journal of Photochemistry and Photobiology B"	"J. Photochem. Photobiol., B")
    ("Journal of Photopolymer Science and Technology"	"J. Photopolym. Sci. Technol.")
    ("Journal of Physics: Conference Series"		"J. Phys. Conf. Ser.")
    ("Journal of Physics: Condensed Matter"		"J. Phys. Condens. Matter")
    ("Journal of Physics A"				"J. Phys. A")
    ("Journal of Physics B"				"J. Phys. B")
    ("Journal of Physics C" 				"J. Phys. C")
    ("Journal of Physics D"				"J. Phys. D")
    ("Journal of Physics F"				"J. Phys. F")
    ("Journal of Physics G"				"J. Phys. G")
    ("Journal of Physical Chemistry"			"J. Phys. Chem.")
    ("Journal of Physical Chemistry A"			"J. Phys. Chem. A")
    ("Journal of Physical Chemistry B"			"J. Phys. Chem. B")
    ("Journal of Physical and Chemical Reference Data"	"J. Phys. Chem. Ref. Data")
    ("Journal of Physics and Chemistry of Solids"	"J. Phys. Chem. Solids")
    ("Journal de Physique I"				"J. Phys. I")
    ("Journal de Physique II"				"J. Phys. II")
    ("Journal de Physique III"				"J. Phys. III")
    ("Journal de Physique IV"				"J. Phys. IV")
    ("Journal of Physical Organic Chemistry"		"J. Phys. Org. Chem.")
    ("Journal of the Physical Society of Japan"		"J. Phys. Soc. Jpn.")
    ("Journal of Planar Chromatography - Modern TLC"	"J. Planar. Chromatogr. - Mod. TLC")
    ("Journal of Plant Biochemistry and Biotechnology"	"J. Plant Biochem. Biotechnol.")
    ("Journal of Polymer Engineering"			"J. Polym. Eng.")
    ("Journal of Polymers and the Environment"		"J. Polym. Environ.")
    ("Journal of Polymer Materials"			"J. Polym. Mater.")
    ("Journal of Polymer Science Part A"		"J. Polym. Sci., Part A")
    ("Journal of Polymer Science Part B"		"J. Polym. Sci., Part B")
    ("Journal of Porous Materials"			"J. Porous Mater.")
    ("Journal of Porphyrins and Phthalocyanines"	"J. Porphyrins Phthalocyanines")
    ("Journal of Power Sources"				"J. Power Sources")
    ("Journal fur Praktische Chemie - Chemiker Zeitung" "J. Prakt. Chem. /Chem-Ztg")
    ("Journal of Propulsion and Power"			"J. Propul. Power")
    ("Journal of Protein Chemistry"			"J. Protein Chem.")
    ("Journal of Pulp and Paper Science"		"J. Pulp Pap. Sci.")
    ("Journal of Quantitative Spectroscopy and Radiative Transfer" "J. Quant. Spectrosc. Radiat. Transfer")
    ("Journal of Radioanalytical and Nuclear Chemistry" "J. Radioanal. Nucl. Chem.")
    ("Journal of Radioanalytical and Nuclear Chemistry Articles" "J. Radioanal. Nucl. Chem. Art.")
    ("Journal of Radioanalytical and Nuclear Chemistry Letters" "J. Radioanal. Nucl. Chem. Lett.")
    ("Journal of Raman Specroscopy"			"J. Raman Spectrosc.")
    ("Journal of Rapid Methods and Automation in Microbiology" "J. Rapid Methods Autom. Microbiol.")
    ("Journal of Reinforced Plastics and Composites"	"J. Reinf. Plast. Compos.")
    ("Journal of Rheology"				"J. Rheol.")
    ("Journal of the South African Institute of Mining and Metallurgy" "J. S. Afr. Inst. Min. Metall.")
    ("Journal of the Science of Food and Agriculture"	"J. Sci. Food Agric.")
    ("Journal of Scientific and Industrial Research"	"J. Sci. Ind. Res.")
    ("Journal of the Serbian Chemical Society" 		"J. Serb. Chem. Soc.")
    ("Journal of Separation Science"			"J. Sep. Sci.")
    ("Journal of Sol-Gel Science and Technology"	"J. Sol-Gel Sci. Technol.")
    ("Journal of Solid State Chemistry"			"J. Solid State Chem.")
    ("Journal of Solid State Electrochemistry"		"J. Solid State Electrochem.")
    ("Journal of Solution Chemistry"			"J. Solution Chem.")
    ("Journal of Steroid Biochemistry and Molecular Biology" "J. Steroid Biochem. Mol. Biol.")
    ("Journal of Strain Analysis for Engineering Design" "J. Strain Anal. Eng. Des.")
    ("Journal of Structural Chemistry"			"J. Struct. Chem.")
    ("Journal of Supercritical Fluids"			"J. Supercrit. Fluids")
    ("Journal of Synthetic Organic Chemistry, Japan"	"J. Synth. Org. Chem Jpn.")
    ("Journal of Testing and Evaluation"		"J. Test. Eval.")
    ("Journal of Thermal Analysis"			"J. Therm. Anal.")
    ("Journal of Thermal Analysis and Calorimetry"	"J. Therm. Anal. Calorim.")
    ("Journal of Thermal Spray Technology"		"J. Therm. Spray Technol.")
    ("Journal of Thermophysics and Heat Transfer"	"J. Thermophys Heat Transfer")
    ("Journal of Thermoplastic Composite Materials"	"J. Thermoplast. Compos. Mater.")
    ("Journal of Toxicology and Environment Health"	"J. Toxicol. Environ. Health")
    ("Journal of Toxicology - Clinical Toxicology"	"J. Toxicol., Clin. Toxicol.")
    ("Journal of Toxicology - Cutaneous and Ocular Toxicology" "J. Toxicol., Cutaneous Ocul. Toxicol.")
    ("Journal of Toxicology - Toxin Reviews"		"J. Toxicol., Toxin Rev.")
    ("Journal of Trace Elements in Experimental Medicine" "J. Trace Elem. Exp. Med.")
    ("Journal of Trace Elements in Medicine and Biology" "J. Trace Elem. Med Biol.")
    ("Journal of Trace and Microprobe Techniques"	"J. Trace Microprobe Tech.")
    ("Journal of Vacuum Science and Technology A"	"J. Vac. Sci. Technol., A")
    ("Journal of Vacuum Science and Technology B"	"J. Vac. Sci. Technol., B")
    ("Journal of Wood Chemistry and Technology"		"J. Wood Chem. Technol.")
    ("Journal of the American Chemical Society"		"JACS")
    ("JOM Journal of the Minerals Metals and Materials Society" "JOM")
    ("JPC Journal of Planar Chromatography Modern TLC" "JPC J. Planar Chromatogr. - Mod. TLC")
    ("Japanese Journal of Applied Physics Part 1"	"Jpn. J. Appl. Phys., Part 1")
    ("Japanese Journal of Applied Physics Part 2"	"Jpn. J. Appl. Phys., Part 2")
    ("Japanese Journal of Cancer Research"		"Jpn. J. Cancer Res.")
    ("Japanese Journal of Pharmacology"			"Jpn. J. Pharmacol.")
    ("Japanese Journal of toxicology and Environment health" "Jpn. J. Toxicol. Environ. Health")
    ("JSME International Journal Series A: Mechanics and Material Engineering" "JSME Int J., Ser. A")
    ("JSME International Journal Series B: Fluids and Thermal Engineering" "JSME Int J., Ser. B")
    ("JSME International Journal Series C: Mechanical Systems Machine Elements and Manufacturing" "JSME Int J., Ser. C")))
