(in-package :bib)

(appendf *abbrev-list*
  '(("Macromolecular Chemistry and Physics"		"Macromol. Chem. Phys.")
    ("Macromolecular Rapid Communications"		"Macromol. Rapid Commun.")
    ("Macromolecular Symposium"				"Macromol. Symp.")
    ("Macromolecular Theory and Simulations"		"Macromol. Theory Simul.")
    ("Magnetic Resonance in Chemistry"			"Magn. Reson. Chem.")
    ("Magnetic Resonance Materials in Physics, Biology and Medicine" "Magn. Reson. Mater. Phys., Biol. Med.")
    ("Magyar Kemiai Folyoirat"				"Magy. Kem. Foly.")
    ("Main Group Chemistry"				"Main Group Chem.")
    ("Main Group Metal Chemistry"			"Main Group Met. Chem.")
    ("Manufacturing Chemist"				"Manuf. Chem.")
    ("Marine Biology"					"Mar. Biol.")
    ("Marine Biotechnology"				"Mar. Biotechnol.")
    ("Marine Chemistry"					"Mar. Chem.")
    ("Marine Environment Research"			"Mar. Environ. Res.")
    ("Marine Pollutution Bulletin"			"Mar. Pollut. Bull.")
    ("Mass Spectrometry Reviews"			"Mass Spectrom. Rev.")
    ("Materials Characterization"			"Mater. Charact.")
    ("Materials Chemistry and Physics"			"Mater. Chem. Phys.")
    ("Materials and Corrosion"				"Mater. Corros.")
    ("Materials and Design"				"Mater. Des.")
    ("Materials Evaluation"				"Mater. Eval.")
    ("Materials Forum"					"Mater. Forum")
    ("Materials at High Temperatures"			"Mater. High Temp.")
    ("Materials Letters"				"Mater. Lett.")
    ("Materials and Manufacturing Processes"		"Mater. Manuf. Processes")
    ("Materials and Organisms"				"Mater. Org.")
    ("Materials Performance"				"Mater. Performance")
    ("Materials Research Bulletin"			"Mater. Res. Bull.")
    ("Materials Research Innovations"			"Mater. Res. Innovations")
    ("Materials Science"				"Mater. Sci.")
    ("Materials Science and Engineering A"		"Mater. Sci. Eng., A")
    ("Materials Science and Engineering B"		"Mater. Sci. Eng., B")
    ("Materials Science and Engineering C"		"Mater. Sci. Eng., C")
    ("Materials Science and Engineering Reports"	"Mater. Sci. Eng., R")
    ("Materials Science Forum"				"Mater. Sci. Forum")
    ("Materials Science in Semiconductor Processing"	"Mater. Sci. Semicond. Process.")
    ("Materials Science Research International"		"Mater. Sci. Res. Int.")
    ("Materials Science and Technology"			"Mater. Sci. Technol.")
    ("Materials and Structures"				"Mater. Struct.")
    ("Materials Transactions, JIM"			"Mater. Trans., JIM")
    ("Materialwissenschaft und Werkstofftechnik"	"Materialwiss. Werkstofftech.")
    ("Matrix Biology"					"Matrix Biol.")
    ("Measurement Science and Technology"		"Meas. Sci. Technol.")
    ("Mechanics of Composite Materials"			"Mech. Compos. Mater.")
    ("Mechanics of Composite Materials and Structures"	"Mech. Compos. Mater. Struct.")
    ("Mechanics of Materials"				"Mech. Mater.")
    ("Mechanics of Time Dependent Materials"		"Mech. Time-Depend. Mater.")
    ("Medicinal Chemistry"				"Med. Chem.")
    ("Medicinal Chemistry Research"			"Med. Chem. Res.")
    ("Mendeleev Communications"				"Mendeleev Commun.")
    ("Metal-Based Drugs"				"Met.-Based Drugs")
    ("Metal Ions in Biological Systems"			"Met. Ions Biol. Syst.")
    ("Metal Science and Heat Treatment"			"Met. Sci. Heat Treat.")
    ("Metabolic Engineering"				"Metab. Eng.")
    ("Metallurgical and Materials Transactions A"	"Metall. Mater. Trans. A")
    ("Metallurgical and Materials Transactions B"	"Metall. Mater. Trans. B")
    ("Metallurgical Transactions A"			"Metall. Trans. A")
    ("Metallurgical Transactions B"			"Metall. Trans. B")
    ("Metallovedenie i Termicheskaya Obrabotka Metallov" "Metalloved. Term. Obrab. Met.")
    ("Methods of Biochemical Analysis"			"Methods Biochem. Anal.")
    ("Methods in Enzymology"				"Methods Enzymol.")
    ("Microbial and Comparative Genomics"		"Microb. Comp. Genomics")
    ("Microbiological Research"				"Microbiol. Res.")
    ("Microchemical Journal"				"Microchem. J.")
    ("Microelectronic Engineering"			"Microelectron. Eng.")
    ("Microelectronics Journal"				"Microelectron. J.")
    ("Microporous Materials"				"Microporous Mater.")
    ("Microporous and Mesoporous Materials"		"Microporous Mesoporous Mater.")
    ("Microscale Thermophysical Engineering"		"Microscale Thermophys. Eng.")
    ("Microscopy and Microanalysis"			"Microsc. Microanal.")
    ("Microscopy Research and Technique"		"Microsc. Res. Tech.")
    ("Mikrochimica Acta"				"Mikrochim. Acta")
    ("Mine Water and the Environment"			"Mine Water Environ.")
    ("Minerals Engineering"				"Miner. Eng.")
    ("Minerals and Metallurgical Processing"		"Miner. Metall. Process")
    ("Mineral Processing and Extractive Metallurgy Review" "Miner. Process. Extr. Metall. Rev.")
    ("Mini - Reviews in Medicinal Chemistry"		"Mini-Rev. Med. Chem.")
    ("Modern Drug Discovery"				"Mod. Drug Discovery")
    ("Modern Physics Letters A"				"Mod. Phys. Lett. A")
    ("Modern Physics Letters B"				"Mod. Phys. Lett. B")
    ("Modelling and Simulation in Materials Science and Engineering" "Modell. Simul. Mater. Sci. Eng.")
    ("Molecular Cancer Therapeutics"			"Mol. Cancer Ther.")
    ("Molecular and Cellular Biochemistry"		"Mol. Cell. Biochem.")
    ("Molecular Crystals and Liquid Crystals Science and Technology Section A" "Mol. Cryst. Liq. Cryst. Sci. Technol., Sect. A")
    ("Molecular Crystals and Liquid Crystals Science and Technology Section C" "Mol. Cryst. Liq. Cryst. Sci. Technol., Sect. C")
    ("Molecular Marine Biology and Biotechnology"	"Mol. Mar. Biol. Biotech.")
    ("Molecular Interventions"				"Mol. Interventions")
    ("Molecular Microbiology"				"Mol. Microbiol.")
    ("Molecular Pharmacology"				"Mol. Pharmacol.")
    ("Molecular Physics"				"Mol. Phys.")
    ("Molecular Reproduction and Development"		"Mol. Reprod. Dev")
    ("Molecular and Supramolecular Photochemistry"	"Mol. Supramol. Photochem.")
    ("Monthy Notices of the Royal Astronomical Society"	"Mon. Not. R. Astron. Soc.")
    ("Monatshefte fur Chemie"				"Monatsh. Chem.")
    ("MRS Bulletin"					"MRS Bull.")
    ("MRS Internet Journal of Nitride Semiconductor Research" "MRS Internet J. Nitride Semicond. Res.")))
