(in-package :bib)

(appendf *abbrev-list*
  '(("Nachrichten aus Chemie Technik und Laboratorium"	"Nachr. Chem. Tech. Lab.")
    ("Nano Letters"				"Nano Lett.")
    ("Nanostructured Materials"			"Nanostruct. Mater.")
    ("Nature" 					"Nat.")
    ("Nature Biotechnology"			"Nat. Biotechnol.")
    ("Nature Communications" 			"Nat. Commun.")
    ("Nature Physics" 				"Nat. Phys.")
    ("Natural Products Letters"			"Nat. Prod. Lett.")
    ("Natural Products Reports"			"Nat. Prod. Rep.")
    ("Natural Product Sciences"			"Nat. Prod. Sci.")
    ("Natural Structural Biology"		"Nat. Struct. Biol.")
    ("Natural Toxins"				"Nat. Toxins")
    ("NATO ASI Series, Series A"		"NATO ASI Ser., Ser. A")
    ("NATO ASI Series, Series B" 		"NATO ASI Ser., Ser. B")
    ("NATO ASI Series, Series C"		"NATO ASI Ser., Ser. C")
    ("NATO ASI Series, Series E"		"NATO ASI Ser., Ser. E")
    ("NATO ASI Series, Series G"		"NATO ASI Ser., Ser. G")
    ("NATO ASI Series, Series H"		"NATO ASI Ser., Ser. H")
    ("Naunyn-Schmiedeberg's Archives of Pharmacology" "Naunyn-Schmiedeberg's Arch. Pharmacol.")
    ("NDT and E International"			"NDT and E Int.")
    ("Neftyanoe Khozyaistvo"			"Neft. Khoz.")
    ("Neorganicheskie Materialy"		"Neorg. Mater.")
    ("Neurochemistry International"		"Neurochem. Int.")
    ("Neurochemical Research"			"Neurochem. Res.")
    ("New Comprehensive Biochemistry"		"New Compr. Biochem.")
    ("New Diamond and Frontier Carbon Technology" "New Diamond Front. Carbon Technol.")
    ("New Journal of Chemistry"			"New J. Chem.")
    ("New Journal of Physics"			"New J. Phys.")
    ("New Polymeric Materials"			"New Polym. Mat.")
    ("NMR in Biomedicine"			"NMR Biomed.")
    ("Nuclear Applications" 			"Nucl. Appl.")
    ("Nuclear Engineering and Design"		"Nucl. Eng. Des.")
    ("Nuclear Fusion"				"Nucl. Fusion")
    ("Nuclear Instruments and Methods in Physical Research Section A" "Nucl. Instrum. Methods Phys. Res., Sect. A")
    ("Nuclear Instruments and Methods in Physical Research Section B" "Nucl. Instrum. Methods Phys. Res., Sect. B")
    ("Nuclear Physics A"			"Nucl. Phys. A")
    ("Nuclear Physics B"			"Nucl. Phys. B")
    ("Nuclear Technology"			"Nucl. Technol.")
    ("Nucleic Acids Research"			"Nucleic Acids Res.")
    ("Numerical Heat Transfer Part A"		"Numer. Heat Transfer, Part A")
    ("Numerical Heat Transfer Part B"		"Numer. Heat Transfer, Part B")
    ("Nuovo Cimento della Societa Italiana di Fisica A" "Nuovo Cimento Soc. Ital. Fis., A")
    ("Nuovo Cimento della Societa Italiana di Fisica B" "Nuovo Cimento Soc. Ital. Fis., B")
    ("Nuovo Cimento della Societa Italiana di Fisica C" "Nuovo Cimento Soc. Ital. Fis., C")
    ("Nuovo Cimento della Societa Italiana di Fisica D" "Nuovo Cimento Soc. Ital. Fis., D")))
