(in-package :bib)

(appendf *abbrev-list*
  '(("Oil and Gas Journal"			"Oil Gas J.")
    ("Optics Communication"			"Opt. Commun.")
    ("Optics Express"				"Opt. Express")
    ("Optics Letters"				"Opt. Lett.")
    ("Optical Materials"			"Opt. Mater.")
    ("Optics and Spectroscopy"			"Opt. Spectrosc.")
    ("Optika i Spektroskopiya"			"Opt Spektrosk.")
    ("Opticheskii Zhurnal"			"Opt. Zh.")
    ("Organic Electronics"			"Org. Electron.")
    ("Organic Geochemistry"			"Org. Geochem.")
    ("Organic Letters"				"Org. Lett.")
    ("Organic Mass Spectrometry"		"Org. Mass Spectrom.")
    ("Organic Preparations and Procedures International" "Org. Prep. Proced. Int.")
    ("Organic Process Research and Development" "Org. Process Res. Dev.")
    ("Organic Reaction Mechanics"		"Org. React. Mech.")
    ("Organohalogen Compounds"			"Organohalogen Compd.")
    ("Organometallic Chemistry"			"Organomet. Chem.")
    ("Origins of Life and Evolution of the Biosphere" "Origins Life Evol. Biosphere")
    ("Oxidation of Metals"			"Oxid. Met.")
    ("Ozone Science and Engineering"		"Ozone Sci. Eng.")))
