(in-package :bib)

(appendf *abbrev-list*
  '(("Particle and Particle Systems Characterization"	"Part. Part. Syst. Char.")
    ("Particulate Science and Technology"		"Part. Sci. Technol.")
    ("Physical Chemistry Chemical Physics"		"Phys. Chem. Chem. Phys.")
    ("Perspectives in Drug Discovery and Design"	"Perspect. Drug Discovery Des.")
    ("Pesticide Biochemistry and Physiology"		"Pestic. Biochem. Physiol.")
    ("Pesticide Outlook"				"Pestic. Outlook")
    ("Petroleum Science and Technology"			"Pet. Sci. Technol.")
    ("Pharmaceutical Chemistry Journal"			"Pharm. Chem. J.")
    ("Pharmacy and Pharmacology Communications"		"Pharm. Pharmacol. Commun.")
    ("Pharmaceutical and Pharmacological Letters"	"Pharm. Pharmacol. Lett.")
    ("Pharmaceutical Research"				"Pharm. Res.")
    ("Pharmaceutical Technology"			"Pharm. Technol.")
    ("Pharmacological Research"				"Pharmacol. Res.")
    ("Phase Transitions"				"Phase Transitions")
    ("Philosophical Magazine A"				"Philos. Mag. A")
    ("Philosophical Magazine B"				"Philos. Mag. B")
    ("Philosophical Magazine Letters"			"Philos. Mag. Lett.")
    ("Philosophical Transactions of the Royal Society of London, Series A" "Philos. Trans. R. Soc. London, Ser. A")
    ("Philosophical Transactions of the Royal Society of London, Series B" "Philos. Trans. R. Soc. London, Ser. B")
    ("Phosphorus Sulfur Silicon and the Related Elements" "Phosphorus, Sulfur Silicon Relat. Elem.")
    ("Photochemistry and Photobiology"			"Photochem. Photobiol.")
    ("Photosynthesis Research"				"Photosynth. Res.")
    ("Physics and Chemistry of Glasses"			"Phys. Chem. Glasses")
    ("Physics and Chemistry of Liquids"			"Phys. Chem. Liq.")
    ("Physics and Chemistry of Minerals"		"Phys. Chem. Miner.")
    ("Physics of Fluids A"				"Phys. Fluids A")
    ("Physics of Fluids B"				"Phys. Fluids B")
    ("Physics Letters A"				"Phys. Lett. A")
    ("Physics Letters B"				"Phys. Lett. B")
    ("Physics Reports" 					"Phys. Rep.")
    ("Physical Review A" 				"Phys. Rev. A")
    ("Physical Review B"				"Phys. Rev. B")
    ("Physical Review C"				"Phys. Rev. C")
    ("Physical Review D" 				"Phys. Rev. D")
    ("Physical Review E"				"Phys. Rev. E")
    ("Physical Review Letters"				"Phys. Rev. Lett.")
    ("Physica Scripta"					"Phys. Scr.")
    ("Physical Status Solidi A"				"Phys. Status Solidi A")
    ("Physical Status Solidi B"				"Phys. Status Solidi B")
    ("Physica A"					"Physica A")
    ("Physica B"					"Physica B")
    ("Physica C"					"Physica C")
    ("Physica D"					"Physica D")
    ("Physica E"					"Physica E")
    ("Physiological and Biochemical Zoology"		"Physiol. Biochem. Zool.")
    ("Physiological Chemistry and Physics and Medical NMR" "Physiol. Chem. Phys. Med. NMR")
    ("Physiologia Plantarum"				"Physiol. Plant.")
    ("Phytochemical Analysis"				"Phytochem. Anal")
    ("Plant Physiology and Biochemistry"		"Plant Physiol. Biochem.")
    ("Planta Medica"					"Planta Med.")
    ("Plasma Chemistry and Plasma Processing"		"Plasma Chem. Plasma Process.")
    ("Plasma Physics and Controlled Fusion"		"Plasma Phys. Controlled Fusion")
    ("Plasmas and Polymers"				"Plasmas Polym.")
    ("Plasma Sources Science and Technology"		"Plasma Sources Sci. Technol.")
    ("Plastics Engineering"				"Plast. Eng.")
    ("Plastics Rubber and Composites Processing and Applications" "Plast. Rubber Compos. Process. Appl.")
    ("Platinum Metals Review"				"Platinum Met. Rev.")
    ("Plating and Surface Finishing"			"Plat. Surf. Finish.")
    ("Polish Journal of chemistry"			"Pol. J. Chem.")
    ("Polycyclic Aromatic Compounds"			"Polycyclic Aromat. Compd.")
    ("Polymers for Advanced Technologies"		"Polym. Adv. Technol.")
    ("Polymer Bulletin"					"Polym. Bull.")
    ("Polymer Composites"				"Polym. Compos.")
    ("Polymer Degradation and Stability"		"Polym. Degrad. Stab.")
    ("Polymer Engineering and Science"			"Polym. Eng. Sci.")
    ("Polymer Gels and Networks"			"Polym. Gels Networks")
    ("Polymer International"				"Polym. Int.")
    ("Polymer Journal"					"Polym. J.")
    ("Polymeric Materials Science and Engineering"	"Polym. Mater. Sci. Eng.")
    ("Polymer Networks and Blends"			"Polym. Networks Blends")
    ("Polymer - Plastics Technology and Engineering"	"Polym. Plast. Technol. Eng.")
    ("Polymers and Polymer Composites"			"Polym. Polym. Compos.")
    ("Polymeric Preprints"				"Polym. Prepr.")
    ("Polymer Reaction Engineering"			"Polym. React. Eng.")
    ("Polymer Recycling"				"Polym. Recycl.")
    ("Polymer testing"					"Polym. Test.")
    ("Powder Diffraction"				"Powder Diffr.")
    ("Powder Metallurgy"				"Powder Metall.")
    ("Powder Metallurgy and Metal Ceramics"		"Powder Metall. Met. Ceram.")
    ("Powder Technology"				"Powder Technol.")
    ("Preparative Biochemistry and Biotechnology"	"Prep. Biochem. Biotechnol.")
    ("Preprints - American Chemical Society, Division of Petroleum Chemistry" "Prepr. - Am. Chem. Soc., Div. Pet. Chem.")
    ("Preprint Papers - American Chemical Society, Division of Fuel Chemistry" "Prepr. Pap. - Am. Chem. Soc., Div. Fuel Chem.")
    ("Proceedings of the Royal Society of London Series A" "Proc. R. Soc. London, Ser. A")
    ("Proceedings of the Royal Society of London Series B" "Proc. R. Soc. London, Ser. B")
    ("Process Biochemistry"				"Process Biochem.")
    ("Process Control and Quality"			"Process Control Qual.")
    ("Process Safety and Environment Protection"	"Process Saf. Environ. Prot.")
    ("Process Safety Progress"				"Process Saf. Prog.")
    ("Progress in Biophysics and Molecular biology"	"Prog. Biophys. Mol. Biol.")
    ("Progress in Biotechnology"			"Prog. Biotechnol.")
    ("Progress in Colloid and Polymer Science"		"Prog. Colloid Polym. Sci.")
    ("Progress in Crystal Growth and Characterization of Materials" "Prog. Cryst. Growth Charact. Mater.")
    ("Progress in Energy and Combustion Science"	"Prog. Energy Combust. Sci.")
    ("Progress in Heterocyclic Chemistry"		"Prog. Heterocycl. Chem.")
    ("Progress in Industrial Microbiology"		"Prog. Ind. Microbiol.")
    ("Progress in Inorganic Chemistry"			"Prog. Inorg. Chem.")
    ("Progress in Lipid Research"			"Prog. Lipid Res.")
    ("Progress in Materials Science"			"Prog. Mater Sci.")
    ("Progress in Nuclear Magnetic Resonance Spectroscopy" "Prog. Nucl. Magn. Reson. Spectrosc.")
    ("Progress in Nuclear Science and Technology" 	"Prog. Nucl. Sci. Technol.")
    ("Progress in Organic Coatings"			"Prog. Org. Coat.")
    ("Progress in Paper Recycling"			"Prog. Pap. Recycl.")
    ("Progress in Polymer Science"			"Prog. Polym. Sci.")
    ("Progress in Reaction Kinetics"			"Prog. React. Kinet.")
    ("Progress in Solid State Chemistry"		"Prog. Solid State Chem.")
    ("Progress in Surface Science"			"Prog. Surf. Sci.")
    ("Protection of Metals"				"Prot. Met.")
    ("Protein Engineering"				"Protein Eng.")
    ("Protein Science"					"Protein Sci.")
    ("Przemysl Chemiczny"				"Przem. Chem.")
    ("Pure and Applied Chemistry"			"Pure Appl. Chem.")))
