(in-package :bib)

(appendf *abbrev-list*
  '(("Radiation Effects and Defects in Solids"		"Radiat Eff. Defects Solids")
    ("Radiation Physics and Chemistry"			"Radiat. Phys. Chem.")
    ("Radiation Protection Dosimetry"			"Radiat. Prot. Dosim.")
    ("Radiation Research"				"Radiat. Res.")
    ("Radiochima Acta"					"Radiochim. Acta")
    ("Rapid Communications in Mass Spectrometry"	"Rapid Commun. Mass Spectrom.")
    ("Rapra Review Reports"				"Rapra Rev. Rep.")
    ("Reactive and Functional Polymers"			"React. Funct. Polym.")
    ("Reaction Kinetics and Catalysis Letters"		"React. Kinet. Catal. Lett.")
    ("Recueil des Travaux Chimiques des Pays-Bas" 	"Recl. Trav. Chim. Pays-Bas")
    ("Refractories and Industrial Ceramics"		"Refract. Ind. Ceram")
    ("Regulatory Toxicology and Pharmacology"		"Regul. Toxicol. Pharm.")
    ("Reports on Progress in Physics"			"Rep. Prog. Phys.")
    ("Research on Chemical Intermediates"		"Res. Chem. Intermed.")
    ("Research Communications in Molecular Pathology and Pharmacology" "Res. Commun. Mol. Pathol. Pharmacol.")
    ("Research in Microbiology"				"Res. Microbiol.")
    ("Reviews in Analytical Chemistry"			"Rev. Anal. Chem.")
    ("Reviews in Chemical Engineering"			"Rev. Chem. Eng.")
    ("Revista de Chimie"				"Rev. Chim.")
    ("Reviews in Computational Chemistry"		"Rev. Comput. Chem.")
    ("Reviews of Environment Contamination and Toxicology" "Rev. Environ. Contam. Toxicol.")
    ("Reviews of Modern Physics" 			"Rev. Mod. Phys.")
    ("Revue Generale de Thermique"			"Rev. Gen. Therm.")
    ("Revue de Metallurgie / Cahiers d'Informations Techniques" "Rev. Metall. / Cah. Inf. Tech.")
    ("Reviews of Physiology Biochemistry and Pharmacology" "Rev. Physiol., Biochem. Pharmacol.")
    ("Revue Roumaine de Chimie"				"Rev. Roum. Chim.")
    ("Review of Scientific Instruments"			"Rev. Sci. Instrum.")
    ("Rheologica Acta"					"Rheol. Acta")
    ("Rubber Chemistry and Technology"			"Rubber Chem. Technol.")
    ("Russian Chemical Bulletin"			"Russ. Chem. Bull.")
    ("Russian Journal of Applied Chemistry"		"Russ. J. Appl. Chem.")
    ("Russian Journal of Bioorganic Chemistry"		"Russ. J. Bioorg. Chem.")
    ("Russion Journal of Coordination Chemistry"	"Russ. J. Coord. Chem.")
    ("Russian Journal of Electrochemistry"		"Russ. J. Electrochem.")
    ("Russian Journal of General Chemistry"		"Russ. J. Gen. Chem.")
    ("Russian Journal of Nondestructive Testing"	"Russ. J. Nondestr. Test.")
    ("Russian Journal of Organic Chemistry"		"Russ. J. Org. Chem.")
    ("Russian Metallurgy"				"Russ. Metall.")))
