(in-package :bib)

(appendf *abbrev-list*
  '(("South African Journal of Chemistry"	"S. Afr. J. Chem.")
    ("SAMPE Journal"				"SAMPE J.")
    ("Scandinavian Journal of Metallurgy"	"Scand. J. Metall.")
    ("Science" 					"Sci.")
    ("Science in China, Series B Chemistry"	"Sci. China, Ser. B")
    ("Science in China, Series E Technological Sciences" "Sci. China, Ser. E")
    ("Science Progress"				"Sci. Prog.")
    ("Science and Technology of Welding and Joining" "Sci. Technol. Weld. Joining")
    ("Science of the Total Environment"		"Sci. Total Environ.")
    ("Scripta Materialia"			"Scripta Mater.")
    ("Semiconductor Science and Technology"	"Semicond. Sci. Technol.")
    ("Sensors and Actuators, A"			"Sens. Actuators, A")
    ("Sensors and Actuators, B"			"Sens. Actuators, B")
    ("Separation and Purification Methods"	"Sep. Purif. Methods")
    ("Separation and Purification Technology"	"Sep. Purif. Technol.")
    ("Separation Science and Technology"	"Sep. Sci. Technol.")
    ("Silicates Industriels"			"Silic. Indus.")
    ("Smart Materials and Structures"		"Smart Mater. Struct.")
    ("Soil Biology and Biochemistry"		"Soil Biol. Biochem.")
    ("Solar Energy Materials and Solar Cells"	"Sol. Energy Mater. Sol. Cells")
    ("Solid State Communications"		"Solid State Commun.")
    ("Solid State Ionics"			"Solid State Ionics")
    ("Solid State Nuclear Magnetic Resonance"	"Solid State Nucl. Magn. Reson.")
    ("Solid State Electronics"			"Solid State Electron.")
    ("Solvent Extraction and Ion Exchange"	"Solvent Extr. Ion Exch.")
    ("Soviet Atomic Energy" 			"Sov. At. Energy")
    ("Spectrochimica Acta"			"Spectrochim. Acta")
    ("Spectrochimica Acta, Part A"		"Spectrochim. Acta, Part A")
    ("Spectrochimica Acta, Part B"		"Spectrochim. Acta, Part B")
    ("Spectroscopy Europe"			"Spectrosc. Eur.")
    ("Spectroscopy Letters"			"Spectrosc. Lett.")
    ("Spectroscopic Properties of Inorganic and Organometallic Compounds" "Spectrosc. Prop. Inorg. Organomet. Compd.")
    ("Speculations in Science and Technology"	"Speculations Sci. Technol.")
    ("Spill Science and Technology Bulletin"	"Spill Sci. Technol. Bull.")
    ("Springer Series in Chemical Physics"	"Springer Ser. Chem. Phys.")
    ("Springer Series in Solid-State Sciences"	"Springer Ser. Solid-State Sci.")
    ("Structure and Bonding"			"Struct. Bond.")
    ("Structural Chemistry"			"Struct. Chem.")
    ("Studies in Natural Products Chemistry"	"Stud. Nat. Prod. Chem.")
    ("Studies in Surface Science and Catalysis"	"Stud. Surf. Sci. Catal.")
    ("Superconductor Science and Technology"	"Supercond. Sci. Technol.")
    ("Superlattices and Microstructures"	"Superlattices Microstruct.")
    ("Supramolecular Chemistry"			"Supramol. Chem.")
    ("Supramolecular Photosensitive and Electroactive Materials" "Supramol. Photosensit. Electroact. Mater.")
    ("Supramolecular Science"			"Supramol. Sci.")
    ("Surface Coatings International"		"Surf. Coat. Int.")
    ("Surface and Coatings Technology"		"Surf. Coat. Technol.")
    ("Surface Engineering"			"Surf. Eng.")
    ("Surface and Interface Analysis"		"Surf. Interface Anal.")
    ("Surface Review and Letters"		"Surf. Rev. Lett.")
    ("Surface Science"				"Surf. Sci.")
    ("Surface Science Reports"			"Surf. Sci. Rep.")
    ("Surface Science Spectra"			"Surf. Sci. Spectra")
    ("Synthetic Communications"			"Synth. Commun.")
    ("Synthetic Metals"				"Synth. Met.")
    ("Synthesis and Reactivity in Inorganic and Metal-Organic Chemistry" "Synth. React. Inorg. Met.-Org. Chem.")))
