(in-package :bib)

(appendf *abbrev-list*
  '(("Tappi Journal"				"Tappi J.")
    ("Tetrahedron Letters"			"Tetrahedron Lett.")
    ("Tetrahedron: Asymmetry"			"Tetrahedron: Asymmetry")
    ("The Journal of Chemical Physics"			"J. Chem. Phys.")
    ("THEOCHEM Journal of Molecular Structure"	"THEOCHEM")
    ("Theoretical and Experimental Chemistry"	"Theor. Exp. Chem.")
    ("Theoretical Chemistry Accounts"		"Theor. Chem. Acc.")
    ("Theoretical Foundations of Chemical Engineering" "Theor. Found. Chem. Eng.")
    ("Theoretical Ecology"			"Theor. Ecol.")
    ("Thermochimica Acta"			"Thermochim. Acta")
    ("Thin Solid Films"				"Thin Solid Films")
    ("Tissue Engineering"			"Tissue Eng.")
    ("Topics in Applied Physics"		"Top. Appl. Phys.")
    ("Topics in Biological and Inorganic Chemistry" "Top. Biol. Inorg. Chem.")
    ("Topics in Catalysis"			"Top. Catal.")
    ("Topics in Current Chemistry"		"Top. Curr. Chem.")
    ("Topics in Inorganic Chemistry"		"Top. Inorg. Chem.")
    ("Topics in Fluorescence Spectroscopy"	"Top. Fluoresc. Spectrosc.")
    ("Toxicology and Applied Pharmacology"	"Toxicol. Appl. Pharmacol.")
    ("Toxicological and Environmental Chemistry" "Toxicol. Environ. Chem.")
    ("Toxicology Letters"			"Toxicol. Lett.")
    ("Toxicological Sciences"			"Toxicol. Sci.")
    ("TRAC Trends in Analytical Chemistry"	"TRAC, Trends Anal. Chem.")
    ("Trace Elements and Electrolytes"		"Trace Elem. Electrolytes")
    ("Transactions of the American Nuclear Society" "Trans. Am. Nucl. Soc.")
    ("Transactions of the American Institute of Mining" "Trans. Am. Inst. Min.")
    ("Transactions of the Institution of Metal Finishing" "Trans. Inst. Met. Finish.")
    ("Transactions of the Institution of Mining and Metallurgy Section A" "Trans. Inst. Min. Metall., Sect. A")
    ("Transactions of the Institution of Mining and Metallurgy Section B" "Trans. Inst. Min. Metall., Sect. B")
    ("Transactions of the Institution of Mining and Metallurgy Section C" "Trans. Inst. Min. Metall., Sect. C")
    ("Transition Metal Chemistry"		"Transition Met. Chem.")
    ("Trends in Biochemical Sciences"		"Trends Biochem. Sci.")
    ("Trends in Biotechnology"			"Trends Biotechnol.")
    ("Tsvetnaya Metally"			"Tsvetn. Met.")))
