(in-package :bib)

(appendf *abbrev-list*
  '(("Zeitschrift fur Anorganische und Allgemeine Chemie"	"Z. Anorg. Allg. Chem.")
    ("Zeitschrift fur Kristallograhie"				"Z. Kristallogr.")
    ("Zeitschrift fur Kristallograhie - New Crystral Stuctures"	"Z. Kristallogr. - New Cryst. Struct.")
    ("Zeitschrift fur MetaIlkunde"				"Z. MetaIlkd.")
    ("Zeitschrift fur Naturforschung A"				"Z. Naturforsch., A")
    ("Zeitschrift fur Naturforschung B"				"Z. Naturforsch., B")
    ("Zeitschrift fur Naturforschung C"				"Z. Naturforsch., C")
    ("Zeitschrift fur Physik A"					"Z. Phys. A")
    ("Zeitschrift fur Physik B" 				"Z. Phys. B")
    ("Zeitschrift fur Physik C"					"Z. Phys. C")
    ("Zeitschrift fur Physik D" 				"Z. Phys. D")
    ("Zeitschrift fur Physikalische Chemie"			"Z. Phys. Chem.")
    ("Zhurnal Fizicheskoi Khimii"				"Zh. Fiz. Khim.")
    ("Zhurnal Neorganicheskoi Khimii"				"Zh. Neorg. Khim.")
    ("Zhurnal Obshchei Khimii"					"Zh. Obshch. Khim.")
    ("Zhurnal Organicheskoi Khimii"				"Zh. Org. Khim.")
    ("Zhurnal Prikladnoi Khimii"				"Zh. Prikl. Khim.")))
