(in-package :bib)

(defun parse-auxfile (auxfile)
  (flet ((bibcitep (line)
	   (scan "^\\\\bibcite" line))
	 (key-from-bibcite (bibcite)
	   (let* ((str (scan-to-strings "{.+?}" bibcite))
		  (len (strlen str)))
	     (substr str 1 (1- len)))))
    (let* ((lines (read-file-lines auxfile))
	   (bibcites (remove-if-not #'bibcitep lines)))
      (mapcar #'key-from-bibcite bibcites))))
