(in-package :bib)

;; 
(defparameter *journal-table* (make-hash-table))

(setf (gethash :jnm *journal-table*) '("Journal of Nuclear Materials" "J. Nucl. Mater."))
(setf (gethash :sci *journal-table*) '("Science" "Sci."))
(setf (gethash :nat *journal-table*) '("Nature" "Nat."))
(setf (gethash :nc *journal-table*) '("Nature Communications" "Nat. Commun."))
(setf (gethash :prl *journal-table*) '("Physical Review Letters" "Phys. Rev. Lett."))
(setf (gethash :prep *journal-table*) '("Physics Reports" "Phys. Rep."))
(setf (gethash :pr *journal-table*) '("Physical Review" "Phys. Rev."))
(setf (gethash :prb *journal-table*) '("Physical Review B" "Phys. Rev. B"))
(setf (gethash :pre *journal-table*) '("Physical Review E" "Phys. Rev. E"))
(setf (gethash :jpcm *journal-table*) '("Journal of Physics: Condensed Matter" "J. Phys. Condens. Matter."))
(setf (gethash :pa *journal-table*) '("Physica A" "Physica A"))
(setf (gethash :pb *journal-table*) '("Physica B" "Physica B"))
(setf (gethash :pc *journal-table*) '("Physica C" "Physica C"))
(setf (gethash :jacs *journal-table*) '("Journal of the American Ceramic Society" "J. Am. Ceram. Soc."))
(setf (gethash :pnst *journal-table*) '("Progress in Nuclear Science and Technology" "Prog. Nucl. Sci. Technol."))
(setf (gethash :jom *journal-table*) '("JOM" "JOM"))
(setf (gethash :jap *journal-table*) '("Journal of Applied Physics" "J. Appl. Phys."))
(setf (gethash :pccp *journal-table*) '("Physical Chemistry Chemical Physics" "PCCP"))
(setf (gethash :aipadv *journal-table*) '("AIP Advances" "AIP Adv."))
(setf (gethash :fp *journal-table*) '("Frontiers of Physics" "Front. Phys."))
